- hosts: localhost
  connection: local

  vars:
#    homebrew_taps:
#      - caskroom/cask
#      - caskroom/versions
#      - homebrew/dupes
#      - homebrew/versions
#      - homebrew/boneyard
#      - homebrew/binary

    homebrew_packages:
      - name: git
      - name: vim
      - name: tig
      - name: tmux
      - name: zsh
      - name: curl
      - name: wget
      - name: jq
      - name: tree
      - name: go
      - name: mysql
      - name: redis

    homebrew_cask_packages:
      - name: iterm2
      - name: macvim
      - name: virtualbox
      - name: vagrant
      - name: google-chrome
      - name: google-japanese-ime
      - name: slack
      - name: chatwork
      - name: workplace-chat
      - name: sequel-pro
      - name: jetbrains-toolbox
      - name: evernote
      - name: skitch
      - name: microsoft-office

  tasks:
    - name: homebrew update
      homebrew:
        update_homebrew: yes

#    - name: homebrew tap
#      homebrew_tap:
#        name: '{{ item }}'
#        state: present
#      with_items: '{{ homebrew_taps }}'

    - name: homebrew packages install
      homebrew:
        name: '{{ item.name }}'
        state: '{{ item.state | default("present") }}'
      with_items: '{{ homebrew_packages }}'

    - name: homebrew cask packages install
      homebrew_cask: name={{ item.name }} state=installed
      # ※1 GUIツールをインストールする場所を `/Application` に固定
      environment:
        HOMEBREW_CASK_OPTS: "--appdir=/Applications"
      with_items: '{{ homebrew_cask_packages }}'
